name: Build and deploy example app and documentation on GitHub pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 18.6.0
      - name: Prepare output folder
        run: |
          mkdir out
      - name: Build table-engine
        run: |
          yarn install --frozen-lockfile
          npm run build
      - name: Build demo app
        run: |
          cd example
          yarn install --frozen-lockfile
          npm run build -- --base-href=https://bennyboer.github.io/table-engine/
          cp -R ./dist/example/* ../out/
      - name: Build documentation app
        run: |
          cd docs/app
          yarn install --frozen-lockfile
          npm run build -- --base-href=https://bennyboer.github.io/table-engine/docs
          mkdir ../../out/docs
          cp -R ./dist/app/* ../../out/docs
      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: out
          token: ${{ secrets.GITHUBPAGESDEPLOYTOKEN }}
